#!/usr/bin/env bash

WASIX_CLANG_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if ! test -f $WASIX_CLANG_DIR/.dependencies-ok ; then
    echo "You are running wasix-clang for the first time. This will take a moment, as we need to fetch dependencies." >&2
    if ! bash $WASIX_CLANG_DIR/setup.sh ; then
        echo "Failed to set up dependencies. Please check the output above for errors." >&2
        exit 1
    fi
fi 

if test -z "$SUDO" && test "$(id -u)" -ne 0 ; then
    SUDO="$(which sudo)"
fi

export PATH="$WASIX_CLANG_DIR/bin:$WASIX_CLANG_DIR/wasix-llvm/bin:$WASIX_CLANG_DIR/wasix-wasmer/bin:$PATH"

export WASIX_SYSROOT="$WASIX_CLANG_DIR/wasix-sysroot"
export WASIX_LLVM="$WASIX_CLANG_DIR/wasix-llvm"
export WASIX_WASMER="$WASIX_CLANG_DIR/wasix-wasmer"

export WASMER="$WASIX_CLANG_DIR/wasix-wasmer/bin/wasmer"
export CC=wasix-clang
export CXX=wasix-clang++
export AR=llvm-ar
export NM=llvm-nm
export LD=wasm-ld
export RANLIB=llvm-ranlib
export AS=llvm-as

# Register Wasmer as a binfmt handler
$SUDO $WASMER binfmt reregister >/dev/null